export const products = {
    data: [
      {
        productName: "Paleta sombras sunshine",
        brand: "Beauty Glazed",
        category: ["Sombras","Skincare"],
        price: "60.000",
        stock: true,
        discount: true,
        newProduct: true,
        advised: true,
        image: "product-0000001.jpg",
        url: "product-1.html",
        brandUrl: "primers.html"
      },
      {
        productName: "producto 2",
        brand: "Beauty Glazed",
        category: "Accesorios",
        price: "3.000",
        stock: true,
        discount: true,
        newProduct: true,
        advised: true,
        image: "product-0000002.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 3",
        brand: "Atenea",
        category: "Sombras",
        price: "18.000",
        stock: true,
        discount: true,
        newProduct: true,
        advised: true,
        image: "product-0000003.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 4",
        brand: "Atenea",
        category: "frer",
        price: "22.000",
        stock: true,
        discount: true,
        newProduct: true,
        advised: false,
        image: "product-0000004.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 5",
        brand: "Atenea",
        category: "erfer",
        price: "8.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: true,
        image: "product-0000143.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 6",
        brand: "Atenea",
        category: "erfer",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: true,
        image: "product-0000005.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 7",
        brand: "Atenea",
        category: "erfer",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: true,
        image: "product-0000006.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 8",
        brand: "Atenea",
        category: "erfer",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "product-0000007.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 9",
        brand: "Atenea",
        category: "erfer",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "product-0000008.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 10",
        brand: "Atenea",
        category: "Bases",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "product-0000009.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 11",
        brand: "Atenea",
        category: "erfer",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "product-0000100.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 12",
        brand: "Atenea",
        category: "Sombras",
        price: "1.200",
        stock: true,
        discount: false,
        newProduct: true,
        advised: true,
        image: "product-0000101.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 13",
        brand: "Atenea",
        category: "Sombras",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "product-0000102.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 14",
        brand: "Atenea",
        category: "erfer",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "product-0000103.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 15",
        brand: "Atenea",
        category: "Tonicos",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "product-0000104.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 16",
        brand: "Atenea",
        category: "Serums",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "product-0000105.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 17",
        brand: "Atenea",
        category: "Rubores",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "product-0000106.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 18",
        brand: "Atenea",
        category: "Primers",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "product-0000107.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 19",
        brand: "Atenea",
        category: "Polvos",
        price: "80.000",
        stock: true,
        discount: true,
        newProduct: true,
        advised: false,
        image: "product-0000108.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 20",
        brand: "Atenea",
        category: "Contornos",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "product-0000109.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 20",
        brand: "Atenea",
        category: "Correctores",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "product-0000109.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 20",
        brand: "Atenea",
        category: "Pestañas",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "product-0000109.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 20",
        brand: "Atenea",
        category: "Mascarillas",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "product-0000109.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 20",
        brand: "Abis",
        category: "Bases",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "product-0000109.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 20",
        brand: "Zara",
        category: "Labios",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "product-0000109.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 20",
        brand: "Atenea",
        category: "jabonesFaciales",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "product-0000109.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 20",
        brand: "Atenea",
        category: "Bases",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "product-0000109.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 20",
        brand: "the factory",
        category: "Iluminadores",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "product-0000109.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 20",
        brand: "Atenea",
        category: ["Cremas","Skincare"],
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "product-0000109.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 20",
        brand: "more",
        category: "Hidratantes",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "product-0000109.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 20",
        brand: "Ruby rose",
        category: "Desmaquillantes",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "product-0000109.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 20",
        brand: "Hous",
        category: "Delineadores",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "product-0000109.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 20",
        brand: "Atenea",
        category: "Delineadores",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "product-0000109.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },

      {
        productName: "producto 20",
        brand: "ff",
        category: "Delineadores",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "product-0000109.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 20",
        brand: "i8hn78y",
        category: "Delineadores",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "product-0000109.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 20",
        brand: "i8hn78y",
        category: "Bases",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "product-0000109.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
      {
        productName: "producto 2200",
        brand: "i8hn78y",
        category: "Bases",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "product-0000109.jpg",
        url: "product-1.html",
        brandUrl: "nuevos-productos.html"
      },
     
     
    ],
  };

  