export const products = {
    data: [
      {
        productName: "Paleta color vibes",
        brand: "Beauty Glazed",
        category: "Sombras",
        price: "60.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: true,
        image: "img-000000001.jpg",
        url: "product-1.html"
      },
      {
        productName: "Paleta color studio",
        brand: "Beauty Glazed",
        category: "Sombras",
        price: "56.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: true,
        image: "img-000000002.jpg",
        url: "paleta-color-studio.html"
      },
      {
        productName: "Paleta hawaii",
        brand: "Atenea",
        category: "Sombras",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: true,
        image: "img-000000003.jpg",
        url: "paleta-hawaii.html"
      },
      {
        productName: "Paleta majestic",
        brand: "Atenea",
        category: "Sombras",
        price: "70.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000004.jpg",
        url: "paleta-majestic.html"
      },
      {
        productName: "Paleta Birds",
        brand: "Atenea",
        category: "Sombras",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: true,
        image: "img-000000005.jpg",
        url: "paleta-Birds.html"
      },
      {
        productName: "Paleta Marvelous",
        brand: "Atenea",
        category: "Sombras",
        price: "70.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: true,
        image: "img-000000006.jpg",
        url: "paleta-marvelous.html"
      },
      {
        productName: "Paleta Art Deco",
        brand: "Atenea",
        category: "Sombras",
        price: "40.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: true,
        image: "img-000000007.jpg",
        url: "paleta-art-deco.html"
      },
      {
        productName: "Paleta Perfect Mix",
        brand: "Beauty Glazed",
        category: "Sombras",
        price: "35.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000008.jpg",
        url: "paleta-perfect-mix.html"
      },
      {
        productName: "Paleta Hono Lulu",
        brand: "Atenea",
        category: "Sombras",
        price: "56.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000009.jpg",
        url: "paleta-hono-lulu.html"
      },
      {
        productName: "Paleta Perfect Neutral",
        brand: "Beauty Glazed",
        category: "Sombras",
        price: "32.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000010.jpg",
        url: "paleta-perfect-neutral.html"
      },
      {
        productName: "Paleta Mystic Glow",
        brand: "Ruby Rose",
        category: "Sombras",
        price: "48.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000011.jpg",
        url: "paleta-mystic-glow.html"
      },
      {
        productName: "Paleta Sublime",
        brand: "Atenea",
        category: "Sombras",
        price: "42.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: true,
        image: "img-000000012.jpg",
        url: "paleta-sublime.html"
      },
      {
        productName: "Paleta Atemporal",
        brand: "Atenea",
        category: "Sombras",
        price: "70.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000013.jpg",
        url: "paleta-atemporal.html"
      },
      {
        productName: "Paleta Thunder",
        brand: "Ushas",
        category: "Sombras",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000014.jpg",
        url: "paleta-thunder.html"
      },
      {
        productName: "Paleta Frutas (Fresa)",
        brand: "Trendy",
        category: "Sombras",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000015.jpg",
        url: "paleta-frutas-fresa.html"
      },
      {
        productName: "Paleta Frutas (Uva)",
        brand: "Trendy",
        category: "Sombras",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000016.jpg",
        url: "paleta-frutas-uva.html"
      },
      {
        productName: "Paleta Frutas (Coco)",
        brand: "Trendy",
        category: "Sombras",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000017.jpg",
        url: "paleta-frutas-coco.html"
      },
      {
        productName: "Paleta Frutas (Durazno)",
        brand: "Trendy",
        category: "Sombras",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000018.jpg",
        url: "paleta-frutas-durazno.html"
      },
      {
        productName: "Sombra Liquida Sublime",
        brand: "Atenea",
        category: "Sombras",
        price: "25.000",
        stock: true,
        discount: true,
        newProduct: true,
        advised: false,
        image: "img-000000019.jpg",
        url: "sombra-liquida-sublime.html"
      },
      {
        productName: "Paleta Blusher",
        brand: "Atenea",
        category: "Rubores",
        price: "30.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000020.jpg",
        url: "paleta-blusher.html"
      },
      {
        productName: "Paleta Divine Baked",
        brand: "Atenea",
        category: "Iluminadores",
        price: "38.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000021.jpg",
        url: "paleta-divine-baked.html"
      },
      {
        productName: "Iluminador Baked Powder",
        brand: "Atenea",
        category: "Iluminadores",
        price: "20.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000022.jpg",
        url: "iluminador-baked-powder.html"
      },
      {
        productName: "Iluminador Corporal (Tono Bronce)",
        brand: "Elaya",
        category: "Iluminadores",
        price: "27.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000023.jpg",
        url: "iluminador-corporal-tono-bronce.html"
      },
      {
        productName: "Iluminador Corporal (Tono Plata)",
        brand: "Elaya",
        category: "Iluminadores",
        price: "27.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000024.jpg",
        url: "iluminador-corporal-tono-plata.html"
      },
      {
        productName: "Iluminador Corporal (Tono Rosa)",
        brand: "Elaya",
        category: "Iluminadores",
        price: "27.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000025.jpg",
        url: "iluminador-corporal-tono-rosa.html"
      },
      {
        productName: "Iluminador Liquido (Tono Champaña)",
        brand: "Elaya",
        category: "Iluminadores",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000026.jpg",
        url: "iluminador-liquido-tono-champaña.html"
      },
      {
        productName: "Iluminador Liquido (Tono Dorado)",
        brand: "Elaya",
        category: "Iluminadores",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000027.jpg",
        url: "iluminador-liquido-tono-dorado.html"
      },
      {
        productName: "Iluminador Liquido (Tono Rosa)",
        brand: "Elaya",
        category: "Iluminadores",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000028.jpg",
        url: "iluminador-liquido-tono-rosa.html"
      },
      {
        productName: "Paleta Iluminadores y Contornos Girl",
        brand: "Ushas",
        category: "Iluminadores",
        price: "19.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000029.jpg",
        url: "paleta-iluminadores-contornos-girl.html"
      },
      {
        productName: "Paleta Cloud",
        brand: "Trendy",
        category: "Iluminadores",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000030.jpg",
        url: "paleta-cloud.html"
      },
      {
        productName: "Iluminador Eclipse Lunar",
        brand: "Trendy",
        category: "Iluminadores",
        price: "12.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000031.jpg",
        url: "iluminador-eclipse-lunar.html"
      },
      {
        productName: "Polvo De Hadas (Tono Rosa)",
        brand: "Dolce Bella",
        category: "Iluminadores",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000032.jpg",
        url: "polvo-de-hadas-tono-rosa.html"
      },
      {
        productName: "Polvo De Hadas (Tono Cobre)",
        brand: "Dolce Bella",
        category: "Iluminadores",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000033.jpg",
        url: "polvo-de-hadas-tono-cobre.html"
      },
      {
        productName: "Polvo De Hadas (Tono Rosa)",
        brand: "Dolce Bella",
        category: "Iluminadores",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000034.jpg",
        url: "polvo-de-hadas-tono-rosa.html"
      },
      {
        productName: "Brow Cocktail Cejas",
        brand: "Trendy",
        category: "Sombras",
        price: "18.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000035.jpg",
        url: "brow-cocktail-cejas.html"
      },
      {
        productName: "Rubor En Crema Love Perfect",
        brand: "Trendy",
        category: "Rubores",
        price: "20.000",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "img-000000036.jpg",
        url: "rubor-en-crema-love-perfect.html"
      },
      {
        productName: "Rubor En Barra Blush Love",
        brand: "Trendy",
        category: "Rubores",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000037.jpg",
        url: "rubor-en-barra-blush-love.html"
      },
      {
        productName: "Polvos Sueltos (Tono 1)",
        brand: "Ame",
        category: "Polvos",
        price: "25.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000038.jpg",
        url: "polvos-sueltos-tono-1.html"
      },
      {
        productName: "Contorno En Polvo",
        brand: "Dolce Bella",
        category: "Contornos",
        price: "16.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000039.jpg",
        url: "contorno-en-polvo.html"
      },
      {
        productName: "Contorno En Barra",
        brand: "Dolce Bella",
        category: "Contornos",
        price: "18.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000040.jpg",
        url: "contorno-en-barra.html"
      },
      {
        productName: "Contorno En Barra Doble Con Rubor",
        brand: "Trendy",
        category: "Contornos",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000041.jpg",
        url: "contorno-en-barra-doble-con-rubor.html"
      },
      {
        productName: "AAA",
        brand: "AAA",
        category: "AAA",
        price: "AAA",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000042.jpg",
        url: "product-1.html"
      },
      {
        productName: "Contorno De Ojos Eye Serum",
        brand: "Trendy",
        category: "Serums",
        price: "12.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000043.jpg",
        url: "contorno-de-ojos-eye-serum.html"
      },
      {
        productName: "Base Tinted (Tono 1)",
        brand: "Ame",
        category: "Bases",
        price: "26.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000044.jpg",
        url: "base-tinted-tono-1.html"
      },
      {
        productName: "Base Larga Duracion (Tono 1)",
        brand: "OG",
        category: "Bases",
        price: "30.000",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "img-000000045.jpg",
        url: "base-larga-duracion-tono-1.html"
      },
      {
        productName: "Base BB Cream (Tono Honey)",
        brand: "Miis Cosmetics",
        category: "Bases",
        price: "12.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000046.jpg",
        url: "base-bb-cream-tono-honey.html"
      },
      {
        productName: "Base BB Cream (Tono Caramel)",
        brand: "Miis Cosmetics",
        category: "Bases",
        price: "12.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000047.jpg",
        url: "base-bb-cream-tono-caramel.html"
      },
      {
        productName: "Corrector Ojos Alta Cobertura",
        brand: "Ruby rose",
        category: "Correctores",
        price: "20.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000048.jpg",
        url: "corrector-ojos-alta-cobertura.html"
      },
      {
        productName: "Corrector Ojos Alta Cobertura",
        brand: "OG",
        category: "Correctores",
        price: "22.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000049.jpg",
        url: "corrector-ojos-alta-cobertura.html"
      },
      {
        productName: "Corrector Liquido Flawless",
        brand: "Ruby rose",
        category: "Correctores",
        price: "13.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000050.jpg",
        url: "corrector-liquido-flawless.html"
      },
      {
        productName: "Corrector Liquido Concealer",
        brand: "Dolce bella",
        category: "Correctores",
        price: "13.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000051.jpg",
        url: "corrector-liquido-concealer.html"
      },
      {
        productName: "Corrector Liquido Ojos",
        brand: "Beauty Glazed",
        category: "Correctores",
        price: "12.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000052.jpg",
        url: "corrector-liquido-ojos.html"
      },
      {
        productName: "Corrector Larga Duracion (Tono 1)",
        brand: "Elaya",
        category: "Correctores",
        price: "12.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000053.jpg",
        url: "corrector-larga-duracion-tono-1.html"
      },
      {
        productName: "Corrector Liquido Camouflage",
        brand: "Ushas",
        category: "Correctores",
        price: "10.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000054.jpg",
        url: "corrector-liquido-camouflage.html"
      },
      {
        productName: "Delineador Perfect Line 2 en 1",
        brand: "Miis Cosmetics",
        category: "Delineadores",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000055.jpg",
        url: "delineador-perfect-line-2-en-1.html"
      },
      {
        productName: "Kit Delineadores x8 Neon Matte Rainbow",
        brand: "Trendy",
        category: "Delineadores",
        price: "40.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000056.jpg",
        url: "kit-delineadores-x8-neon-matte-rainbow.html"
      },
      {
        productName: "Delineador Doble",
        brand: "Trendy",
        category: "Delineadores",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000057.jpg",
        url: "delineador-doble.html"
      },
      {
        productName: "Delineador Plumon Pin Up",
        brand: "Trendy",
        category: "Delineadores",
        price: "10.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000058.jpg",
        url: "delineador-plumon-pin-up.html"
      },
      {
        productName: "Delineador Plumon Super Black",
        brand: "Ushas",
        category: "Delineadores",
        price: "12.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000059.jpg",
        url: "delineador-plumon-super-black.html"
      },
      {
        productName: "Lapiz Delineador",
        brand: "Dolce Bella",
        category: "Delineadores",
        price: "10.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000060.jpg",
        url: "lapiz-delineador.html"
      },
      {
        productName: "Delineador Liquido Spring",
        brand: "Ushas",
        category: "Delineadores",
        price: "11.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000061.jpg",
        url: "delineador-liquido-spring.html"
      },
      {
        productName: "Delineador glitter (Varios tonos)",
        brand: "Ushas",
        category: "Delineadores",
        price: "10.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: true,
        image: "img-000000062.jpg",
        url: "delineador-glitter-varios-tonos.html"
      },
      {
        productName: "Pestañina Collosal 7x Waterproof",
        brand: "Maybeline",
        category: "Pestañas",
        price: "35.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000063.jpg",
        url: "pestañina-collosal-7x-waterproof.html"
      },
      {
        productName: "Pestañina Collosal 36h",
        brand: "Maybeline",
        category: "Pestañas",
        price: "37.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000064.jpg",
        url: "pestañina-collosal-36h.html"
      },
      {
        productName: "Pestañina False Lash Effect",
        brand: "Dolce Bella",
        category: "Pestañas",
        price: "16.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000065.jpg",
        url: "pestañina-false-lash-effect.html"
      },
      {
        productName: "Mascara De Pestañas Boom",
        brand: "Trendy",
        category: "Pestañas",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000066.jpg",
        url: "mascara-de-pestañas-boom.html"
      },
      {
        productName: "Mascara De Pestañas Supreme",
        brand: "Atenea",
        category: "Pestañas",
        price: "17.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000067.jpg",
        url: "mascara-de-pestañas-supreme.html"
      },
      {
        productName: "Mascara De Pestañas Profesional",
        brand: "Dolce Bella",
        category: "Pestañas",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000068.jpg",
        url: "mascara-de-pestañas-profesional.html"
      },
      {
        productName: "Mascara De Pestañas Fortalecedora Fresh",
        brand: "Trendy",
        category: "Pestañas",
        price: "10.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000069.jpg",
        url: "mascara-de-pestañas-fortalecedora-fresh.html"
      },
      {
        productName: "Gel Fijador De Cejas",
        brand: "Trendy",
        category: "Cejas",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000070.jpg",
        url: "gel-fijador-de-cejas.html"
      },
      {
        productName: "Serum Crecimiento Pestañas",
        brand: "Trendy",
        category: "Pestañas",
        price: "30.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000071.jpg",
        url: "serum-crecimiento-pestañas.html"
      },
      {
        productName: "Jabon De Cejas",
        brand: "Trendy",
        category: "Cejas",
        price: "12.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000072.jpg",
        url: "jabon-de-cejas.html"
      },
      {
        productName: "Face Primer",
        brand: "Dolce Bella",
        category: "Primers",
        price: "30.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000073.jpg",
        url: "face-primer.html"
      },
      {
        productName: "Primer Prebase Mate",
        brand: "Elaya",
        category: "Primers",
        price: "26.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: true,
        image: "img-000000074.jpg",
        url: "primer-prebase-mate.html"
      },
      {
        productName: "Primer Serum Summer",
        brand: "Trendy",
        category: "Primers",
        price: "25.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000075.jpg",
        url: "primer-serum-summer.html"
      },
      {
        productName: "Primer Serum Water Melon",
        brand: "Trendy",
        category: "Primers",
        price: "25.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000076.jpg",
        url: "primer-serum-water-melon.html"
      },
      {
        productName: "Spray Fijador De Maquillaje",
        brand: "Dolce Bella",
        category: "Primers",
        price: "25.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000077.jpg",
        url: "spray-fijador-de-maquillaje-dolcebella.html"
      },
      {
        productName: "Spray Fijador De Maquillaje",
        brand: "Trendy",
        category: "Primers",
        price: "25.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000078.jpg",
        url: "spray-fijador-de-maquillaje-trendy.html"
      },
      {
        productName: "Aceite Desmaquillante",
        brand: "Ame",
        category: "Desmaquillantes",
        price: "18.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000079.jpg",
        url: "aceite-desmaquillante-ame.html"
      },
      {
        productName: "Aceite desmaquillante",
        brand: "Trendy",
        category: "Desmaquillantes",
        price: "25.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000080.jpg",
        url: "aceite-desmaquillante-trendy.html"
      },
      {
        productName: "Espuma Desmaquillante De Pestañas",
        brand: "Trendy",
        category: "Desmaquillantes",
        price: "25.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000081.jpg",
        url: "espuma-desmaquillante-de-pestañas.html"
      },
      {
        productName: "Desmaquillador Con Proteina De Leche",
        brand: "Dolce Bella",
        category: "Desmaquillantes",
        price: "14.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000082.jpg",
        url: "desmaquillador-con-proteina-de-leche.html"
      },
      {
        productName: "Jabon Facial Limpieza Purificante En Gel",
        brand: "Ruby Rose",
        category: "jabonesFaciales",
        price: "27.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000083.jpg",
        url: "jabon-facial-limpieza-purificante-en-gel.html"
      },
      {
        productName: "Jabon Facial Liquido",
        brand: "Dolce Bella",
        category: "jabonesFaciales",
        price: "24.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000084.jpg",
        url: "jabon-facial-liquido-dolcebella.html"
      },
      {
        productName: "Jabon Facial Liquido",
        brand: "Trendy",
        category: "jabonesFaciales",
        price: "35.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000085.jpg",
        url: "jabon-facial-liquido-trendy.html"
      },
      {
        productName: "Jabon Facial Liquido Para Hombre",
        brand: "Trendy",
        category: "Jabones",
        price: "35.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000086.jpg",
        url: "jabon-facial-liquido-para-hombre.html"
      },
      {
        productName: "Serum De Vitamina C",
        brand: "Bioaqua",
        category: "Serums",
        price: "28.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000087.jpg",
        url: "serum-de-vitamina-c.html"
      },
      {
        productName: "Serum Acido Hialuronico",
        brand: "Bioaqua",
        category: "Serums",
        price: "25.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000088.jpg",
        url: "serum-acido-hialuronico.html"
      },
      {
        productName: "Serum acido hialuronico",
        brand: "Dolce Bella",
        category: "Serums",
        price: "38.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000089.jpg",
        url: "serum-acido-hialuronico-dolcebella.html"
      },
      {
        productName: "Oleo Facial Anti Envejecimiento",
        brand: "Dolce Bella",
        category: "Serums",
        price: "38.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000090.jpg",
        url: "oleo-facial-anti-envejecimiento.html"
      },
      {
        productName: "Suero Facial Renovador Celular",
        brand: "Dolce Bella",
        category: "Serums",
        price: "38.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000091.jpg",
        url: "suero-facial-renovador-celular.html"
      },
      {
        productName: "Suero Facial Antioxidante",
        brand: "Ruby Rose",
        category: "Serums",
        price: "34.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000092.jpg",
        url: "suero-facial-antioxidante-rubyrose.html"
      },
      {
        productName: "Acido Hialuronico en crema",
        brand: "Dolce Bella",
        category: "Serums",
        price: "20.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000093.jpg",
        url: "acido-hialuronico-en-crema.html"
      },
      {
        productName: "Suero Facial Con Filtro UV",
        brand: "Dolce Bella",
        category: "Serums",
        price: "22.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000094.jpg",
        url: "suero-facial-con-filtro-uv.html"
      },
      {
        productName: "Tonico en spray de aloe vera",
        brand: "Bioaqua",
        category: "Tonicos",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: true,
        image: "img-000000095.jpg",
        url: "tonico-en-spray-de-aloe-vera.html"
      },
      {
        productName: "Tonico Rosas y Manzanilla (240 ml)",
        brand: "Trendy",
        category: "Tonicos",
        price: "20.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000096.jpg",
        url: "tonico-rosas-y-Manzanilla-240ml.html"
      },
      {
        productName: "Tonico De Rosas (250 ml)",
        brand: "Lula",
        category: "Tonicos",
        price: "20.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000097.jpg",
        url: "tonico-de-rosas-250ml.html"
      },
      {
        productName: "Agua Micelar Pureactive (400ml)",
        brand: "Garnier",
        category: "Tonicos",
        price: "30.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000098.jpg",
        url: "agua-micelar-pureactive-400ml.html"
      },
      {
        productName: "Agua Micelar (240ml)",
        brand: "Dolce Bella",
        category: "Tonicos",
        price: "18.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000099.jpg",
        url: "agua-micelar-dolcebella-240ml.html"
      },
      {
        productName: "Gel Hidratante Aloe Vera",
        brand: "Trendy",
        category: "Hidratantes",
        price: "50.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000100.jpg",
        url: "gel-hidratante-aloe-vera.html"
      },
      {
        productName: "Spray Hidratante De Vitamina C",
        brand: "Bioaqua",
        category: "Hidratantes",
        price: "10.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000101.jpg",
        url: "spray-hidratante-de-vitamina-c.html"
      },
      {
        productName: "Hidratante labios strawberry",
        brand: "Trendy",
        category: "Hidratantes",
        price: "10.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000102.jpg",
        url: "hidratante-labios-strawberry.html"
      },
      {
        productName: "Mascarilla Facial Exfoliante",
        brand: "Ruby Rose",
        category: "Mascarillas",
        price: "27.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000103.jpg",
        url: "mascarilla-facial-exfoliante.html"
      },
      {
        productName: "Mascarilla En Gel Exfoliante De Arroz",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "22.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000104.jpg",
        url: "mascarilla-en-gel-exfoliante-de-arroz.html"
      },
      {
        productName: "Mascarilla Hidrogel De Pepino Ojos",
        brand: "Trendy",
        category: "Mascarillas",
        price: "20.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000105.jpg",
        url: "mascarilla-hidrogel-de-pepino-ojos.html"
      },
      {
        productName: "Mascarilla De Arcilla",
        brand: "Dolce Bella",
        category: "Mascarillas",
        price: "17.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000106.jpg",
        url: "mascarilla-de-arcilla.html"
      },
      {
        productName: "Mascarilla Carbon Activado",
        brand: "Bioaqua",
        category: ["Mascarillas","Skincare"],
        price: "25.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000107.jpg",
        url: "mascarilla-carbon-activado.html"
      },
      {
        productName: "Gel Aloe Vera Pink",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "20.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000108.jpg",
        url: "gel-aloe-vera-pink.html"
      },
      {
        productName: "Mascarilla Hidratante Aloe Vera",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000109.jpg",
        url: "mascarilla-hidratante-aloe-vera-bioaqua.html"
      },
      {
        productName: "Mascarilla Exfoliante Dual",
        brand: "Dolce Bella",
        category: "Mascarillas",
        price: "25.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000110.jpg",
        url: "mascarilla-exfoliante-dual.html"
      },
      {
        productName: "Mascarilla Hidratante Te Verde",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "3.500",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000111.jpg",
        url: "mascarilla-hidratante-te-verde.html"
      },
      {
        productName: "Mascarilla Hidratante Miel",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "3.500",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000112.jpg",
        url: "mascarilla-hidratante-miel.html"
      },
      {
        productName: "Mascarilla Hidratante Aloe Vera",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "3.500",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000113.jpg",
        url: "mascarilla-hidratante-aloe-vera.html"
      },
      {
        productName: "Mascarilla Hidratante Pepino",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "3.500",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000114.jpg",
        url: "mascarilla-hidratante-pepino.html"
      },
      {
        productName: "Mascarilla Hidratante Esencia De Rosas",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "3.500",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000115.jpg",
        url: "mascarilla-hidratante-esencia-de-rosas.html"
      },
      {
        productName: "Mascarilla Hidratante Velo Hombre",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "5.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000116.jpg",
        url: "mascarilla-hidratante-velo-hombre.html"
      },
      {
        productName: "Mascarilla Acido Hialuronico + Esencia De Centella",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "5.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000117.jpg",
        url: "mascarilla-acido-hialuronico-esencia-de-centella.html"
      },
      {
        productName: "Mascarilla Hidratante De Colageno",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "5.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000118.jpg",
        url: "mascarilla-hidratante-de-colageno.html"
      },
      {
        productName: "Mascarilla Antiacne",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "6.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000119.jpg",
        url: "mascarilla-antiacne.html"
      },
      {
        productName: "Kit parche ojos y labios",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "5.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000120.jpg",
        url: "kit-parche-ojos-y-labios.html"
      },
      {
        productName: "Mascarilla Algas Marinas Ojos",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "3.500",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000121.jpg",
        url: "mascarilla-algas-marinas-ojos.html"
      },
      {
        productName: "Mascarilla De Nanopeptidos Ojos",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "3.500",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000122.jpg",
        url: "mascarilla-de-nanopeptidos-ojos.html"
      },
      {
        productName: "Mascarilla Colageno Oro Para Ojos",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "3.500",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000123.jpg",
        url: "mascarilla-colageno-oro-para-ojos.html"
      },
      {
        productName: "Colageno Para Labios Cherry (20 Unidades)",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "20.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000124.jpg",
        url: "colageno-para-labios-cherry.html"
      },
      {
        productName: "Mascarilla Puntos Negros",
        brand: "Trendy",
        category: "Mascarillas",
        price: "4.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000125.jpg",
        url: "mascarilla-puntos-negros.html"
      },
      {
        productName: "Mantequilla Corporal",
        brand: "Trendy",
        category: "Cremas",
        price: "25.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000126.jpg",
        url: "mantequilla-corporal.html"
      },
      {
        productName: "Crema Hidratante De Vitamina C",
        brand: "Bioaqua",
        category: "Cremas",
        price: "22.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000127.jpg",
        url: "crema-hidratante-de-vitamina-c.html"
      },
      {
        productName: "Crema Antimanchas Blanqueadora",
        brand: "Bioaqua",
        category: "Cremas",
        price: "20.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000128.jpg",
        url: "crema-antimanchas-blanqueadora.html"
      },
      {
        productName: "Crema Contorno De Ojos y Arrugas Para Hombre",
        brand: "Trendy",
        category: "Cremas",
        price: "30.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000129.jpg",
        url: "crema-contorno-de-ojos-y-arrugas-para-hombre.html"
      },
      {
        productName: "Beauty Blender Profesional",
        brand: "Trendy",
        category: "Accesorios",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000130.jpg",
        url: "beauty-blender-profesional.html"
      },
      {
        productName: "Limpiador Instantaneo De Brochas",
        brand: "Lula",
        category: "Accesorios",
        price: "24.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000131.jpg",
        url: "limpiador-instantaneo-de-brochas.html"
      },
      {
        productName: "Jabon Limpiador De Brochas En Seco",
        brand: "Atenea",
        category: "Accesorios",
        price: "28.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000132.jpg",
        url: "jabon-limpiador-de-brochas-en-seco.html"
      },
      {
        productName: "Jabon Liquido Limpiador De Brochas",
        brand: "Trendy",
        category: "Accesorios",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000133.jpg",
        url: "jabon-liquido-limpiador-de-brochas.html"
      },
      {
        productName: "Shampoo para brochas",
        brand: "Trendy",
        category: "Accesorios",
        price: "12.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000134.jpg",
        url: "shampoo-para-brochas.html"
      },
      {
        productName: "Paleta Mezcladora",
        brand: "Trendy",
        category: "Accesorios",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000135.jpg",
        url: "paleta-mezcladora.html"
      },
      {
        productName: "Tapete Limpia Brochas",
        brand: "Trendy",
        category: "Accesorios",
        price: "10.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000136.jpg",
        url: "tapete-limpia-brochas.html"
      },
      {
        productName: "Toalla Magica Desmaquillante",
        brand: "Magic Makeup",
        category: "Accesorios",
        price: "12.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: true,
        image: "img-000000137.jpg",
        url: "toalla-magica-desmaquillante.html"
      },
      {
        productName: "Separador De Pestañas",
        brand: "Trendy",
        category: "Accesorios",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000138.jpg",
        url: "separador-de-pestañas.html"
      },
      {
        productName: "Kit Brochas De Ojos x12",
        brand: "Trendy",
        category: "Accesorios",
        price: "25.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000139.jpg",
        url: "kit-brochas-de-ojos-x12-trendy.html"
      },
      {
        productName: "Kit Brochas De Ojos x12",
        brand: "Purpure",
        category: "Accesorios",
        price: "18.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000140.jpg",
        url: "kit-brochas-de-ojos-x12-purpure.html"
      },
      {
        productName: "Kit Brochas De Ojos x12 + Estuche",
        brand: "Shinee Beauty & Cosmetics",
        category: "Accesorios",
        price: "30.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000141.jpg",
        url: "kit-brochas-de-ojos-x12-shinee.html"
      },
      {
        productName: "Jabon Liquido Facial Trendy + Sachet Pequeño",
        brand: "Trendy",
        category: "Jabones",
        price: "45.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000142.jpg",
        url: "jabon-liquido-facial-trendy-sachet-pequeño.html"
      },
      {
        productName: "Sachet Tonico De Rosas y Manzanilla",
        brand: "Trendy",
        category: "Accesorios",
        price: "8.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000143.jpg",
        url: "sachet-tonico-de-rosas-y-manzanilla.html"
      },
      {
        productName: "Sachet Grande Jabon Liquido Facial",
        brand: "Trendy",
        category: "Accesorios",
        price: "25.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000144.jpg",
        url: "sachet-grande-jabon-liquido-facial.html"
      },
      {
        productName: "Lip gloss Sweet As mellon",
        brand: "Ushas",
        category: "Labios",
        price: "10.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000145.jpg",
        url: "lip-gloss-sweet-as-mellon.html"
      },
      {
        productName: "Kit x6 Delineadores Perlados",
        brand: "Trendy",
        category: "Delineadores",
        price: "35.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000146.jpg",
        url: "kit-x6-delineadores-perlados.html"
      },
      {
        productName: "Polvos Sueltos (Varios Tonos)",
        brand: "Trendy",
        category: "Polvos",
        price: "20.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000147.jpg",
        url: "polvos-sueltos-varios-tonos-trendy.html"
      },
      {
        productName: "Corrector Liquido Magic Concealer",
        brand: "Trendy",
        category: "Correctores",
        price: "12.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "img-000000148.jpg",
        url: "corrector-liquido-magic-concealer.html"
      }
    ],
  };


 