export const products = {
    data: [
      {
        productName: "Paleta color vibes",
        brand: "Beauty Glazed",
        category: "Sombras",
        price: "60.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: true,
        image: "Product-1.jpg"
      },
      {
        productName: "Paleta color studio",
        brand: "Beauty Glazed",
        category: "Sombras",
        price: "56.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: true,
        image: "Product-1.jpg"
      },
      {
        productName: "Paleta hawaii",
        brand: "Atenea",
        category: "Sombras",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: true,
        image: "Product-1.jpg"
      },
      {
        productName: "Paleta majestic",
        brand: "Atenea",
        category: "Sombras",
        price: "70.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Paleta Birds",
        brand: "Atenea",
        category: "Sombras",
        price: "80.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: true,
        image: "Product-1.jpg"
      },
      {
        productName: "Paleta Marvelous",
        brand: "Atenea",
        category: "Sombras",
        price: "70.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: true,
        image: "Product-1.jpg"
      },
      {
        productName: "Paleta Art Deco",
        brand: "Atenea",
        category: "Sombras",
        price: "40.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: true,
        image: "Product-1.jpg"
      },
      {
        productName: "Paleta Perfect Mix",
        brand: "Beauty Glazed",
        category: "Sombras",
        price: "35.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Paleta Hono Lulu",
        brand: "Atenea",
        category: "Sombras",
        price: "56.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Paleta Perfect Neutral",
        brand: "Beauty Glazed",
        category: "Sombras",
        price: "32.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Paleta Mystic Glow",
        brand: "Ruby Rose",
        category: "Sombras",
        price: "48.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Paleta Sublime",
        brand: "Atenea",
        category: "Sombras",
        price: "42.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: true,
        image: "Product-1.jpg"
      },
      {
        productName: "Paleta Atemporal",
        brand: "Atenea",
        category: "Sombras",
        price: "70.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Paleta Thunder",
        brand: "Ushas",
        category: "Sombras",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Paleta Frutas (Fresa)",
        brand: "Trendy",
        category: "Sombras",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Paleta Frutas (Uva)",
        brand: "Trendy",
        category: "Sombras",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Paleta Frutas (Coco)",
        brand: "Trendy",
        category: "Sombras",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Paleta Frutas (Durazno)",
        brand: "Trendy",
        category: "Sombras",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Sombra Liquida Sublime",
        brand: "Atenea",
        category: "Sombras",
        price: "25.000",
        stock: true,
        discount: true,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Paleta Blusher",
        brand: "Atenea",
        category: "Rubores",
        price: "30.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Paleta Divine Baked",
        brand: "Atenea",
        category: "Iluminadores",
        price: "38.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Iluminador Baked Powder",
        brand: "Atenea",
        category: "Iluminadores",
        price: "20.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Iluminador Corporal (Tono Bronce)",
        brand: "Elaya",
        category: "Iluminadores",
        price: "27.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Iluminador Corporal (Tono Plata)",
        brand: "Elaya",
        category: "Iluminadores",
        price: "27.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Iluminador Corporal (Tono Rosa)",
        brand: "Elaya",
        category: "Iluminadores",
        price: "27.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Iluminador Liquido (Tono Champaña)",
        brand: "Elaya",
        category: "Iluminadores",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Iluminador Liquido (Tono Dorado)",
        brand: "Elaya",
        category: "Iluminadores",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Iluminador Liquido (Tono Rosa)",
        brand: "Elaya",
        category: "Iluminadores",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Paleta Iluminadores y Contornos Girl",
        brand: "Ushas",
        category: "Iluminadores",
        price: "19.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Paleta Cloud",
        brand: "Trendy",
        category: "Iluminadores",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Iluminador Eclipse Lunar",
        brand: "Trendy",
        category: "Iluminadores",
        price: "12.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Polvo De Hadas (Tono Rosa)",
        brand: "Dolce Bella",
        category: "Iluminadores",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Polvo De Hadas (Tono Cobre)",
        brand: "Dolce Bella",
        category: "Iluminadores",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Polvo De Hadas (Tono Rosa)",
        brand: "Dolce Bella",
        category: "Iluminadores",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Brow Cocktail Cejas",
        brand: "Trendy",
        category: "Sombras",
        price: "18.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Rubor En Crema Love Perfect",
        brand: "Trendy",
        category: "Rubores",
        price: "20.000",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Rubor En Barra Blush Love",
        brand: "Trendy",
        category: "Rubores",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Polvos Sueltos (Tono 1)",
        brand: "Ame",
        category: "Polvos",
        price: "25.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Contorno En Polvo",
        brand: "Dolce Bella",
        category: "Contornos",
        price: "16.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Contorno En Barra",
        brand: "Dolce Bella",
        category: "Contornos",
        price: "18.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Contorno En Barra Doble Con Rubor",
        brand: "Trendy",
        category: "Contornos",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Contorno De Ojos Eye Serum",
        brand: "Trendy",
        category: "Serums",
        price: "12.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Base Tinted (Tono 1)",
        brand: "Ame",
        category: "Bases",
        price: "26.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Base Larga Duracion (Tono 1)",
        brand: "OG",
        category: "Bases",
        price: "30.000",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Base BB Cream (Tono Honey)",
        brand: "Miis Cosmetics",
        category: "Bases",
        price: "12.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Base BB Cream (Tono Caramel)",
        brand: "Miis Cosmetics",
        category: "Bases",
        price: "12.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Corrector Ojos Alta Cobertura",
        brand: "Ruby rose",
        category: "Correctores",
        price: "20.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Corrector Ojos Alta Cobertura",
        brand: "OG",
        category: "Correctores",
        price: "22.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Corrector Liquido Flawless",
        brand: "Ruby rose",
        category: "Correctores",
        price: "13.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Corrector Liquido Concealer",
        brand: "Dolce bella",
        category: "Correctores",
        price: "13.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Corrector Liquido Ojos",
        brand: "Beauty Glazed",
        category: "Correctores",
        price: "12.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Corrector Larga Duracion (Tono 1)",
        brand: "Elaya",
        category: "Correctores",
        price: "12.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Corrector Liquido Camouflage",
        brand: "Ushas",
        category: "Correctores",
        price: "10.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Delineador Perfect Line 2 en 1",
        brand: "Miis Cosmetics",
        category: "Delineadores",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Kit Delineadores x8 Neon Matte Rainbow",
        brand: "Trendy",
        category: "Delineadores",
        price: "40.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Delineador Doble",
        brand: "Trendy",
        category: "Delineadores",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Delineador Plumon Pin Up",
        brand: "Trendy",
        category: "Delineadores",
        price: "10.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Delineador Plumon Super Black",
        brand: "Ushas",
        category: "Delineadores",
        price: "12.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Lapiz Delineador",
        brand: "Dolce Bella",
        category: "Delineadores",
        price: "10.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Delineador Liquido Spring",
        brand: "Ushas",
        category: "Delineadores",
        price: "11.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Delineador glitter (Varios tonos)",
        brand: "Ushas",
        category: "Delineadores",
        price: "10.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: true,
        image: "Product-1.jpg"
      },
      {
        productName: "Pestañina Collosal 7x Waterproof",
        brand: "Maybeline",
        category: "Pestañas",
        price: "35.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Pestañina Collosal 36h",
        brand: "Maybeline",
        category: "Pestañas",
        price: "37.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Pestañina False Lash Effect",
        brand: "Dolce Bella",
        category: "Pestañas",
        price: "16.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Mascara De Pestañas Boom",
        brand: "Trendy",
        category: "Pestañas",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Mascara De Pestañas Supreme",
        brand: "Atenea",
        category: "Pestañas",
        price: "17.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Mascara De Pestañas Profesional",
        brand: "Dolce Bella",
        category: "Pestañas",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Mascara De Pestañas Fortalecedora Fresh",
        brand: "Trendy",
        category: "Pestañas",
        price: "10.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Gel Fijador De Cejas",
        brand: "Trendy",
        category: "Cejas",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Serum Crecimiento Pestañas",
        brand: "Trendy",
        category: "Pestañas",
        price: "30.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Jabon De Cejas",
        brand: "Trendy",
        category: "Cejas",
        price: "12.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Face Primer",
        brand: "Dolce Bella",
        category: "Primers",
        price: "30.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Primer Prebase Mate",
        brand: "Elaya",
        category: "Primers",
        price: "26.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: true,
        image: "Product-1.jpg"
      },
      {
        productName: "Primer Serum Summer",
        brand: "Trendy",
        category: "Primers",
        price: "25.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Primer Serum Water Melon",
        brand: "Trendy",
        category: "Primers",
        price: "25.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Spray Fijador De Maquillaje",
        brand: "Dolce Bella",
        category: "Primers",
        price: "25.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Spray Fijador De Maquillaje",
        brand: "Trendy",
        category: "Primers",
        price: "25.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Aceite Desmaquillante",
        brand: "Ame",
        category: "Desmaquillantes",
        price: "18.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Aceite desmaquillante",
        brand: "Trendy",
        category: "Desmaquillantes",
        price: "25.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Espuma Desmaquillante De Pestañas",
        brand: "Trendy",
        category: "Desmaquillantes",
        price: "25.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Desmaquillador Con Proteina De Leche",
        brand: "Dolce Bella",
        category: "Desmaquillantes",
        price: "14.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Jabon Facial Limpieza Purificante En Gel",
        brand: "Ruby Rose",
        category: "jabonesFaciales",
        price: "27.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Jabon Facial Liquido",
        brand: "Dolce Bella",
        category: "jabonesFaciales",
        price: "24.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Jabon Facial Liquido",
        brand: "Trendy",
        category: "jabonesFaciales",
        price: "35.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Jabon Facial Liquido Para Hombre",
        brand: "Trendy",
        category: "Jabones",
        price: "35.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Serum De Vitamina C",
        brand: "Bioaqua",
        category: "Serums",
        price: "28.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Serum Acido Hialuronico",
        brand: "Bioaqua",
        category: "Serums",
        price: "25.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Serum acido hialuronico",
        brand: "Dolce Bella",
        category: "Serums",
        price: "38.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Oleo Facial Anti Envejecimiento",
        brand: "Dolce Bella",
        category: "Serums",
        price: "38.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Suero Facial Renovador Celular",
        brand: "Dolce Bella",
        category: "Serums",
        price: "38.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Suero Facial Antioxidante",
        brand: "Ruby Rose",
        category: "Serums",
        price: "34.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Acido Hialuronico en crema",
        brand: "Dolce Bella",
        category: "Serums",
        price: "20.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Suero Facial Con Filtro UV",
        brand: "Dolce Bella",
        category: "Serums",
        price: "22.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Tonico en spray de aloe vera",
        brand: "Bioaqua",
        category: "Tonicos",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: true,
        image: "Product-1.jpg"
      },
      {
        productName: "Tonico Rosas y Manzanilla (240 ml)",
        brand: "Trendy",
        category: "Tonicos",
        price: "20.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Tonico De Rosas (250 ml)",
        brand: "Lula",
        category: "Tonicos",
        price: "20.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Agua Micelar Pureactive (400ml)",
        brand: "Garnier",
        category: "Tonicos",
        price: "30.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Agua Micelar (240ml)",
        brand: "Dolce Bella",
        category: "Tonicos",
        price: "18.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Gel Hidratante Aloe Vera",
        brand: "Trendy",
        category: "Hidratantes",
        price: "50.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Spray Hidratante De Vitamina C",
        brand: "Bioaqua",
        category: "Hidratantes",
        price: "10.000",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Hidratante labios strawberry",
        brand: "Trendy",
        category: "Hidratantes",
        price: "10.000",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Mascarilla Facial Exfoliante",
        brand: "Ruby Rose",
        category: "Mascarillas",
        price: "27.000",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Mascarilla En Gel Exfoliante De Arroz",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "22.000",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Mascarilla Hidrogel De Pepino Ojos",
        brand: "Trendy",
        category: "Mascarillas",
        price: "20.000",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Mascarilla De Arcilla",
        brand: "Dolce Bella",
        category: "Mascarillas",
        price: "17.000",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Mascarilla Carbon Activado",
        brand: "Bioaqua",
        category: ["Mascarillas","Skincare"],
        price: "25.000",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Gel Aloe Vera Pink",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "20.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Mascarilla Hidratante Aloe Vera",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Mascarilla Exfoliante Dual",
        brand: "Dolce Bella",
        category: "Mascarillas",
        price: "25.000",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Mascarilla Hidratante Te Verde",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "3.500",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Mascarilla Hidratante Miel",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "3.500",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Mascarilla Hidratante Aloe Vera",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "3.500",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Mascarilla Hidratante Pepino",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "3.500",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Mascarilla Hidratante Esencia De Rosas",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "3.500",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Mascarilla Hidratante Velo Hombre",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "5.000",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Mascarilla + Esencia De Centella",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "5.000",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Mascarilla Hidratante De Colageno",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "5.000",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Mascarilla Antiacne",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "6.000",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Kit parche ojos y labios",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "5.000",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Mascarilla Algas Marinas Ojos",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "3.500",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Mascarilla De Nanopeptidos Ojos",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "3.500",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Mascarilla Colageno Oro Para Ojos",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "3.500",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Colageno Para Labios Cherry (20 Unidades)",
        brand: "Bioaqua",
        category: "Mascarillas",
        price: "20.000",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Mascarilla Puntos Negros",
        brand: "Trendy",
        category: "Mascarillas",
        price: "4.000",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Mantequilla Corporal",
        brand: "Trendy",
        category: "Cremas",
        price: "25.000",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Crema Hidratante De Vitamina C",
        brand: "Bioaqua",
        category: "Cremas",
        price: "22.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Crema Antimanchas Blanqueadora",
        brand: "Bioaqua",
        category: "Cremas",
        price: "20.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Crema Contorno De Ojos y Arrugas Para Hombre",
        brand: "Trendy",
        category: "Cremas",
        price: "30.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Beauty Blender Profesional",
        brand: "Trendy",
        category: "Accesorios",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Limpiador Instantaneo De Brochas",
        brand: "Lula",
        category: "Accesorios",
        price: "24.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Jabon Limpiador De Brochas En Seco",
        brand: "Atenea",
        category: "Accesorios",
        price: "28.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Jabon Liquido Limpiador De Brochas",
        brand: "Trendy",
        category: "Accesorios",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Shampoo para brochas",
        brand: "Trendy",
        category: "Accesorios",
        price: "12.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Paleta Mezcladora",
        brand: "Trendy",
        category: "Accesorios",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Tapete Limpia Brochas",
        brand: "Trendy",
        category: "Accesorios",
        price: "10.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Toalla Magica Desmaquillante",
        brand: "Magic Makeup",
        category: "Accesorios",
        price: "12.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: true,
        image: "Product-1.jpg"
      },
      {
        productName: "Separador De Pestañas",
        brand: "Trendy",
        category: "Accesorios",
        price: "15.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Kit Brochas De Ojos x12",
        brand: "Trendy",
        category: "Accesorios",
        price: "25.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Kit Brochas De Ojos x12",
        brand: "Purpure",
        category: "Accesorios",
        price: "18.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Kit Brochas De Ojos x12 + Estuche",
        brand: "Shinee Beauty & Cosmetics",
        category: "Accesorios",
        price: "30.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Jabon Liquido Facial Trendy + Sachet Pequeño",
        brand: "Trendy",
        category: "Jabones",
        price: "45.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Sachet Tonico De Rosas y Manzanilla",
        brand: "Trendy",
        category: "Accesorios",
        price: "8.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Sachet Grande Jabon Liquido Facial",
        brand: "Trendy",
        category: "Accesorios",
        price: "25.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Lip gloss Sweet As mellon",
        brand: "Ushas",
        category: "Labios",
        price: "10.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Kit x6 Delineadores Perlados",
        brand: "Trendy",
        category: "Delineadores",
        price: "35.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Polvos Sueltos (Varios Tonos)",
        brand: "Trendy",
        category: "Polvos",
        price: "20.000",
        stock: true,
        discount: false,
        newProduct: true,
        advised: false,
        image: "Product-1.jpg"
      },
      {
        productName: "Corrector Liquido Magic Concealer",
        brand: "Trendy",
        category: "Correctores",
        price: "12.000",
        stock: true,
        discount: false,
        newProduct: false,
        advised: false,
        image: "Product-1.jpg"
      }
    ],
  };


 